/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int EXTENDS = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int NEW = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int READ = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int SUPER = 21;
  /** RegularExpression Id. */
  int CHAR = 22;
  /** RegularExpression Id. */
  int BOOLEAN = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int int_constant = 25;
  /** RegularExpression Id. */
  int string_constant = 26;
  /** RegularExpression Id. */
  int null_constant = 27;
  /** RegularExpression Id. */
  int intLiteral = 28;
  /** RegularExpression Id. */
  int floatliteral = 29;
  /** RegularExpression Id. */
  int stringliteral = 30;
  /** RegularExpression Id. */
  int IDENT = 31;
  /** RegularExpression Id. */
  int LETTER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int LPAREN = 34;
  /** RegularExpression Id. */
  int RPAREN = 35;
  /** RegularExpression Id. */
  int LBRACE = 36;
  /** RegularExpression Id. */
  int RBRACE = 37;
  /** RegularExpression Id. */
  int LBRACKET = 38;
  /** RegularExpression Id. */
  int RBRACKET = 39;
  /** RegularExpression Id. */
  int SEMICOLON = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int DOT = 42;
  /** RegularExpression Id. */
  int ASSIGN = 43;
  /** RegularExpression Id. */
  int GT = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int EQ = 46;
  /** RegularExpression Id. */
  int LE = 47;
  /** RegularExpression Id. */
  int GE = 48;
  /** RegularExpression Id. */
  int NEQ = 49;
  /** RegularExpression Id. */
  int PLUS = 50;
  /** RegularExpression Id. */
  int MINUS = 51;
  /** RegularExpression Id. */
  int STAR = 52;
  /** RegularExpression Id. */
  int SLASH = 53;
  /** RegularExpression Id. */
  int REM = 54;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 55;
  /** RegularExpression Id. */
  int INVALID_CONST = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int linecomment = 1;
  /** Lexical state. */
  int blockcomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"// (LETTER | DIGIT)*\"",
    "\"/* (LETTER | DIGIT | \\\'\\n\\\' | \\\'\\r\\\')* */\"",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<intLiteral>",
    "<floatliteral>",
    "<stringliteral>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
